### ISSUE TITLE
Feature request - sorting of mentions.

### ISSUE THREAD

**Issue by SillyPilleus** [zerok/webmentiond#14]
Would it be possible to be able to sort webmentions that are received in a slightly more comprehensive way - I can see the lists getting quite large if lots are received. Perhaps sorting by source or target domain?

Cheers!

**Comment by zerok** [comment]
Do you mean in the admin backend or in the widget? :)

**Comment by ChrisShire** [comment]
apologies, I should have been clearer - in the backend.

**Comment by jlelse** [comment]
Currently those are limited to 50. We should also add pagination support to the UI.

**Comment by zerok** [comment]
Definitely. Perhaps I'll have some time for it tomorrow.

**Comment by zerok** [comment]
Paging is now in the main branch (Docker image should be available in the next couple of minutes) :) As for sorting and filtering: That's next on my list :)

**Comment by ChrisShire** [comment]
Paging working nicely - nice one!
Is it possible to delete mentions? Or will they stay in the "rejected" list forever?

**Comment by zerok** [comment]
Right now you can only reject or delete mentions directly from the database. I'm not sure if deleting is an actual use-case, though.

**Comment by ChrisShire** [comment]
In my case I have a large amounts from the webmention.rocks site and some from my own test - I'll give it a go just editing the database directly.

**Comment by zerok** [comment]
Ahhh, good point 🙂 I'll try to schedule it in before the extended filtering and sorting options 🙂 once I have my laptop back and don't have to work on a Windows machine this should be done rather quickly 😂

**Comment by ChrisShire** [comment]
No problem, my productivity grinds to a halt on windows...

Last question - will different post types use different font-awesome icons in the widget? I can see that comments get "fa fa-comment" and there are a variety for rsvp's- will replies, likes and reposts also get icons? For me they all render as a link.

Sorry for all the questions!

**Comment by zerok** [comment]
Non worries 🙂 I'm currently working on a little custom iconset as a fallback if fontawesome is not available 🙂 Otherwise, if you have a FontAwesome Pro license, the icons there should fit for most mention types 🙂

**Comment by zerok** [comment]
Likes already get a heart but repost doesn't yet have anything special. Suggestions welcome 😁

**Comment by ChrisShire** [comment]
That's weird, hearts aren't displaying for my received likes, just a link icon. Could it be something I've configured incorrectly?

**Comment by zerok** [comment]
Probably just a typo somewhere in the code 🙂 Will look I into it 🙂

**Comment by zerok** [comment]
New likes should now being properly highlighted. For existing ones you'll have to update them manually (either via a new send operation or by updating their type in the database to "like") 😄

**Comment by ChrisShire** [comment]
> New likes should now being properly highlighted. For existing ones you'll have to update them manually (either via a new send operation or by updating their type in the database to "like") 😄

Works great! Thanks!
