### ISSUE TITLE
Interoperability with local postfix for SMTP

### ISSUE THREAD

**Issue by kixiQu** [zerok/webmentiond#21]
In order to get it to work on a local port without having to fight with CAs and such, I ended up abandoning Docker and changing the mailer's SendWithTLS to Send,  and passing nil in place of m.auth. 

```
-       err := msg.SendWithTLS(m.addr, m.auth, m.tlsConfig)
+       err := msg.Send(m.addr, nil)
```

If there were a way to configure this that'd be nice -- but short of that, a callout in a doc would have made it more straightforward to arrive on this.

**Comment by zerok** [comment]
Good point 🙂 I’ll try to find a way to make that configurable and document it properly 😅
