### ISSUE TITLE
Expose metrics on different port

### ISSUE THREAD

**Issue by shivjm** [zerok/webmentiond#34]
Would it be possible to make the metrics available on a separate port instead of the main port? I’d like to block access to them, and it makes sense to me, at least, that administrative routes would be accessed through different means.

**Comment by zerok** [comment]
Yupp, makes sense :) I will try to implement that in the next week :)

**Comment by zerok** [comment]
Hey :) You can now specify the address the metrics should be exposed on via `--metrics-addr`. This flag is set to an empty address by default so that no metrics are exposed by default. You can also set the flag to the same value as the addr flag to get the same behavior as before :)

**Comment by shivjm** [comment]
Awesome! Thank you very much!
