### ISSUE TITLE
nitpick: why is the jwt secret specified by a flag instead of an env var

### ISSUE THREAD

**Issue by ForestJohnson** [zerok/webmentiond#43]
I changed this on my fork because I think that for usage in docker, unless I am missing something, the env var is more secure. Wouldn't an unprivileged user on the host machine be able to see it in the process list? am I wrong? :thinking: tbh i dont know.

**Comment by zerok** [comment]
Hi 🙂  There is also the way of passing it through a configuration file, but you're right: The flag-option should be replaced with an environment variable. I'll try to change that in the next couple of days.

**Comment by ForestJohnson** [comment]
https://git.sequentialread.com/forest/webmentiond/commit/a19bf08a2008656233e82c1d26c44a03dcd31567

**Comment by zerok** [comment]
Yupp, I pretty much did the same but with an additional prefix for the variable and the old flag being kept in place until v2 happens.
