### ISSUE TITLE
Add a config file instead of env variables ? 

### ISSUE THREAD

**Issue by hyde-stevenson** [zerok/webmentiond#5]
Hello,

Wouldn't it be preferable not to have password in an ENV variable ? 
I would prefer a config file to store all these information that only a specific user could read only the file. 

What do you think?

**Comment by zerok** [comment]
That's a bit of a hot topic as some folks prefer environment variables while others prefer configuration files. There are some technical reasons why configuration files would be preferable in some circumstances but environment variables, on the other hand, have the advantage that you could just change some settings for a specific run while keeping all other settings untouched.

At this point, I'd prefer it if we stay with environment variables for now and wait and see if we need more settings that would require complex structures.

**Comment by YarmoM** [comment]
What some containers do is that the password (as an ENV) is only necessary once. When the user is created, the password ENV can be safely removed.

Other solution is putting the password in an external .env file and calling it in the docker-compose file.

FWIW, I'd vote against an extra conf file. But it's up to maintainer :)

**Comment by jlelse** [comment]
Probably both would be possible with https://github.com/spf13/viper

**Comment by zerok** [comment]
Hmm... good point. I'll try to create a little prototype-PR in the next couple of days 🙂

**Comment by zerok** [comment]
@hyde-stevenson I've created a PR that now also allows for providing a configuration file :) (for a sample file run `webmentiond config init`). If you have a minute, could you please try [this binary](https://files.zerokspot.com/releases/webmentiond/snapshots/d0e3d9135f6276e00ca3173bb7b134108dcc8ce3/webmentiond_d0e3d9135f6276e00ca3173bb7b134108dcc8ce3_linux_amd64.zip) if this works for you? Thanks :)
