### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by thomasjsn** [zerok/webmentiond#53]
Hello, When trying this package I encountered a few things.

I didn't want to use Docker, so I instead downloaded the repo and built it with `make`. But I also had to run `npm install` and `npx webpack` in the frontend folder. Maybe this should be included in the documentation?

When trying to run the app without the required environment variables, the error message says `EMAIL_x` but the correct parameter seems to be `MAIL_x`.

After doing this I was able to get it running, but how do I fetch the webmentions? Is there an API or something?

Sorry for my ignorance :)

**Comment by zerok** [comment]
Hi 😄 

Sorry about the `EMAIL_` configuration mix-up.  I'm going to fix that ASAP!

I'll also update the documentation for the frontend 🙂 

As for how to get to the mentions: The easiest way would be to embed a snippet like this onto your page where you want to show the mentions:

```
<div class="webmentions webmentions-container"
    data-endpoint="https://your-site.com/webmentions"
    data-target="https://your-site.com/this-page"></div>
<script src="/webmentions/ui/dist/widget.js"></script>
```

This assumes that webmentiond is available on https://your-site.com/webmentions :)

Internally, this would then fetch the mentions using this request:

```
GET https://your-site.com/webmentions/get?target=https://your-site.com/this-page
```

You can see a complete example with some data flying around on https://zerokspot.com/weblog/2022/01/28/self-hosted-comments-with-remark42/ 

I hope this helps until I can update the documentation 😞

**Comment by thomasjsn** [comment]
Thanks for the explanations and quick response, I'll dig around some more :slightly_smiling_face:

**Comment by zerok** [comment]
The documentation now also explains how to build the project from source and the Linux binaries from now on also contain the CSS and JS files once again :) Closing this ticket now :)

**Comment by thomasjsn** [comment]
Nice, thanks 🙂
