### ISSUE TITLE
Apache as a reverse proxy?

### ISSUE THREAD

**Issue by ChrisShire** [zerok/webmentiond#8]
Thanks for developing webmentiond! I was going to ask this on Mastodon, but saw that this had been created instead...

I have webmentiond installed on my docker host and am playing with it. The reverse proxy guide on [your site is super helpful](https://zerokspot.com/weblog/2020/06/14/setting-up-webmentiond/), but I’m struggling to make it work with apache! I host a few different sites with different virtualhost files.

The relevant section of my virtualhost file is;
```
    <Location /webmentions/>
      ProxyPreserveHost On
      ProxyPass http://<docker host ip>:35080/
      ProxyPassReverse http://<docker host ip>:35080/
    </Location>
```
But I'm having issues with a trailing slash. When I visit `https://mysite.com/webmentions` I get a "requested URL was not found on this server" message.

When I add a trailing slash (e.g. `https://mysite.com/webmentions/`) it redirects to `https://mysite.com/webmentions//ui/#/login` and I'm able to send email & login etc. Not sure why there's a double slash between webmentions and ui in the URL though.

Lastly, when I `curl -i https://mysite.com/webmentions/receive` I get `HTTP/1.1 405 Method Not Allowed.`

If anyone has any tips on how to make this work with apache they would be gratefully received. I use apache as a reverse proxy for a number of services so don't really want to reinvent the wheel and learn Caddy just for this...

**Comment by zerok** [comment]
Hi 🙂 Thanks for giving webmentiond a try!

I haven't used Apache in quite a while but perhaps it would be enough in your case to just remove the tailing `/` from your ProxyPass/ProxyPassReverse lines?

```
      ProxyPass http://<docker host ip>:35080
      ProxyPassReverse http://<docker host ip>:35080
```

As for the `/receive` endpoint: That only accepts HTTP Post calls so the 405 response is correct 🙂

**Comment by ChrisShire** [comment]
Cheers for the response - It seems to be working ok. I'll test further at the weekend when I have some time. I really appreciate the widget that can be embedded in your site!

**Comment by ChrisShire** [comment]
Works with the trailing slashes, just have to remember to have the trailing slash on the end of the url (eg `https://site.com/webmentions/` instead of `https://site.com/webmentions`). No biggie I guess.

For anyone else looking to solve this problem, the section of my virtualhost config is;
```
        <Location /webmentions/>
         ProxyPreserveHost On
         ProxyPass http://<docker host ip>:35080/
         ProxyPassReverse http://<docker host ip>:35080/
         RedirectMatch 404 ^/webmentions/metrics$
        </Location>
```
