### ISSUE TITLE
Parser issue: finds the wrong `title` element

### ISSUE THREAD

**Issue by Seirdy** [zerok/webmentiond#81]
On pages such as [this Smashing Magazine article](https://www.smashingmagazine.com/the-smashing-newsletter/smashing-newsletter-issue-406/), webmentiond parses the last `title` element it sees, even if that title element is not part of the `head` section. The result is that the page's title is assumed to be "Clear Search", even though that's actually the title of an `svg` document embedded in the page.

**Comment by zerok** [comment]
Hi :) Sorry for the delay. I will try to find some time for it next week!

**Comment by zerok** [comment]
Found some time already :D Can you please try with the most recent build?
